### ISSUE TITLE
Can't build numpy

### ISSUE THREAD

**Issue by nmilosev** [eliteraspberries/python-androidenv#2]
When building numpy per instructions:

```
SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.
```

Even though `python3.8-dev` is installed and `Python.h` is in `/usr/include/python3.8`. Any ideas? 

Thanks!

**Comment by mansourmoufid** [comment]
It's necessary to build Python first, then NumPy, because NumPy needs a Python that was also built for Android.

I've added a script named [build-numpy.sh](https://github.com/eliteraspberries/python-androidenv/blob/master/build-numpy.sh) to do this. Please try it:

    /bin/sh build-numpy.sh

Only Python 3.7.11 and NumPy 1.20.3 work for now...

If it is successful, you should find both Python and NumPy in the `build` directory.

**Comment by nmilosev** [comment]
Thank you, will test soon.
